export const ActionTypes = {
    ADD_TRANSACTION : "ADD_TRANSACTION",
    TRANSACTION_LIST : "TRANSACTION_LIST",
    DELETE_TRANSACTION : "DELETE_TRANSACTION",
    // FILTER_PRODUCT_BY_CATEGORY : "FILTER_PRODUCT_BY_CATEGORY",
}